# Generated by Django 5.1.6 on 2025-02-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Roll_No', models.CharField(max_length=20, unique=True)),
                ('Birth_Date', models.DateField(default='2000-01-01')),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Contact_No', models.CharField(max_length=10, unique=True)),
                ('Admission_No', models.CharField(max_length=20, unique=True)),
                ('Academic_Year', models.CharField(default='2024-25', max_length=9)),
            ],
        ),
    ]
