# Generated by Django 5.1.6 on 2025-03-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_student_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Birth_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
