# Generated by Django 5.1.6 on 2025-03-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_alter_student_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Birth_Date',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
