# Generated by Django 5.1.6 on 2025-03-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_student_address_student_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mother_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
