# Generated by Django 5.1.6 on 2025-03-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0007_student_mother_contact_student_mother_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Board_10',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Board_12',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Pass_10',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Percentage_10',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Percentage_12',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='School_10',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='School_12',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Year_12',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
