# Generated by Django 5.1.6 on 2025-03-21 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0008_student_board_10_student_board_12_student_pass_10_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Board_10',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Board_12',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Pass_10',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Percentage_10',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Percentage_12',
        ),
        migrations.RemoveField(
            model_name='student',
            name='School_10',
        ),
        migrations.RemoveField(
            model_name='student',
            name='School_12',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Year_12',
        ),
    ]
