# Generated by Django 5.1.6 on 2025-04-25 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0010_student_hsc_board_student_hsc_marks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sem1_marks',
            new_name='sem_1',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='sem2_marks',
            new_name='sem_2',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='sem3_marks',
            new_name='sem_3',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='sem4_marks',
            new_name='sem_4',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='sem5_marks',
            new_name='sem_5',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='sem6_marks',
            new_name='sem_6',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='sem7_marks',
            new_name='sem_7',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='sem8_marks',
            new_name='sem_8',
        ),
    ]
