# Generated by Django 5.1.6 on 2025-04-25 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0011_rename_sem1_marks_student_sem_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sem_1',
            new_name='sem1_marks',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='sem_2',
            new_name='sem2_marks',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='sem_3',
            new_name='sem3_marks',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='sem_4',
            new_name='sem4_marks',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='sem_5',
            new_name='sem5_marks',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='sem_6',
            new_name='sem6_marks',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='sem_7',
            new_name='sem7_marks',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='sem_8',
            new_name='sem8_marks',
        ),
    ]
